change_task
Oleg595/Intelligent_Placer pull request #2
Opened 2022-02-20 17:23 UTC by Oleg595

2022-02-21 20:47 UTC, DariaWelt requested changes
1. [images/examples/image20.jpg](https://github.com/Oleg595/Intelligent_Placer/pull/2/files#diff-8cc00e71e51fb2014d351e40b6755ee5562c81018216cdb382ee7db3d0ad6b44) - граница чашки выходит за границу листка
2. polygon_cords.txt - пустой. На мой взгляд, чтобы считать датасет подготовленным, стоит заполнить этот файл, тем более на изображениях в main уже есть набор координат. Но, может, Вы предполагаете сделать это позже
3. Думаю, стоит добавить ограничение на минимальную сторону предмета на изображении, чтобы не позволять делать снимки объектов с тонкими или слившимися с фоном границами (это запретит снять листок бумаги очень далеко от поверхности так, что он занимает 10х10 пикселей).

В целом постановка задачи мне очень понравилась, все конкретно.

2022-02-21 20:47 UTC, DariaWelt commented on README.md
> +5. Предметы должны иметь чётко выраженные границы.
Мне кажется, этот и следующий пункт лучше изменить так, чтобы требование стало измеримым. Скорее всего сюда подойдет ограничение на градиент на границе

2022-02-25 18:38 UTC, HellInsider commented on README.md
>  3. Предметы должны располагаться на белом листе бумаги формата A4.
Может ли один и тот же предмет встречаться дважды?

2022-02-26 20:51 UTC, Dannikk approved these changes
С учетом комментариев других ревьеров все выглядит хорошо. Единственное: некоторые требования хотелось бы видеть измеримыми (это, конечно, больше требование к некоторому коммерческому проекту, но есть ощущение, что указать стоит)
Также стоит отметить, что некоторые в пулл реквкесте не отслеживаются, например, пункт "Постановка задачи", в котором есть такая опечатка "фотогрфию"

2022-03-06 13:14 UTC, Oleg595 commented on README.md
> +5. Предметы должны иметь чётко выраженные границы.
Исправлено

2022-03-06 13:14 UTC, Oleg595 commented on README.md
>  3. Предметы должны располагаться на белом листе бумаги формата A4.
Нет, теперь это указано в readme. Благодарю.

2022-03-12 12:40 UTC, merged